"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { siteConfig } from "./site-config";

type Language = "en" | "es";
type Content = Record<string, string | string[]>;

const content: Record<Language, Content> = {
  es: {
    nav: ["Inicio", "Servicios", "Nosotros", "Industrias", "Recursos", "Contacto"], schedule: "Agenda una consulta", skip: "Saltar al contenido", eyebrow: "Soluciones contables, tributarias y empresariales",
    hero: "Construimos empresas más sólidas.", heroAccent: "Protegemos tu crecimiento.", heroText: "Asesoría clara y estratégica para emprendedores, empresas en crecimiento e inversionistas que operan entre Estados Unidos y Colombia.", discover: "Conoce nuestros servicios",
    servicesLabel: "Nuestros servicios", servicesTitle: "Decisiones más claras. Negocios más fuertes.", servicesText: "Soluciones integrales para tus obligaciones, tu estructura y el siguiente paso de tu empresa.",
    coverageLabel: "Cobertura", coverageTitle: "Trabajamos contigo en Estados Unidos y Colombia.", coverageNote: "El alcance se confirma según tu situación, jurisdicción y necesidades.",
    planningLabel: "Planeación tributaria", planningTitle: "Las decisiones tributarias se planean antes de declarar.", planningText: "Una estrategia personalizada ayuda a identificar oportunidades, anticipar obligaciones y tomar decisiones con mayor claridad.", planningDisclosure: "Información educativa general; no constituye asesoría tributaria o legal individual.", planningCta: "Solicita una revisión tributaria",
    resourcesLabel: "Tips y recursos", resourcesTitle: "Información para decidir mejor.", resourcesText: "Contenido práctico para entender tu situación financiera y tributaria. No reemplaza una asesoría personalizada.", instagram: "Ver en Instagram", comingSoon: "Próximamente",
    videosLabel: "Aprende con Contax", videosTitle: "Videos para avanzar con confianza.", videosText: "Una biblioteca en crecimiento de guías breves, explicadas en lenguaje claro.", allVideos: "Ver todos los videos",
    whyLabel: "Por qué Contax", whyTitle: "Más que contadores, tus aliados estratégicos.", processLabel: "Nuestro proceso", processTitle: "Cinco pasos hacia una mejor decisión.",
    industriesLabel: "Industrias a las que servimos", industriesTitle: "Soluciones que entienden tu operación.", partnersLabel: "Aliados estratégicos", partnersTitle: "Una red que amplía tus posibilidades.", partnersText: "Espacio para presentar aliados confirmados que complementan cada solución.",
    testimonialsLabel: "La confianza de nuestros clientes", testimonialsTitle: "Historias que pronto compartiremos.", testimonialsText: "Publicaremos testimonios con la autorización expresa de cada cliente.", share: "Compartir mi experiencia",
    ctaLabel: "Empecemos conversando", ctaTitle: "¿Listo para un futuro financiero más claro?", ctaText: "Cuéntanos dónde estás hoy y a dónde quieres llevar tu empresa. Definamos el siguiente paso.",
    footerText: "Soluciones contables, tributarias y empresariales con visión de largo plazo.", explore: "Explora", contact: "Contacto", legal: "Todos los derechos reservados.",
    services: ["Contabilidad", "Impuestos personales y corporativos", "Creación de empresas", "Nómina / Payroll", "Asesoría contable y financiera", "ITIN Application Assistance"],
    serviceText: ["Información financiera ordenada para tomar mejores decisiones.", "Preparación y acompañamiento para cumplir con claridad.", "La estructura adecuada para empezar y crecer con seguridad.", "Procesos de nómina organizados y oportunos.", "Una perspectiva estratégica para cada etapa de tu negocio.", "Acompañamiento para gestionar tu proceso de ITIN."],
    usa: ["Impuestos personales y corporativos", "ITIN para personas elegibles", "Formación de LLC y Corporations", "Contabilidad y nómina"], colombia: ["Contabilidad y reportes financieros", "Orientación tributaria y de cumplimiento", "Formalización de empresas y negocios", "Asesoría financiera y estratégica"],
    resources: ["Planeación tributaria", "Cómo organizar tus gastos deducibles", "Fechas clave para tu empresa"], resourceTypes: ["REEL DE INSTAGRAM", "ARTÍCULO", "GUÍA"],
    videos: ["¿Qué es la planeación tributaria y por qué tu negocio la necesita?", "Deducciones fiscales que muchos empresarios olvidan", "LLC vs Corporation: ¿cuál conviene más?", "ITIN: requisitos y proceso paso a paso"],
    reasons: ["Experiencia y conocimiento", "Enfoque personalizado", "Confianza y transparencia", "Tecnología a tu favor"], reasonText: ["Conocimiento técnico y experiencia práctica para ver el panorama completo.", "Soluciones a la medida de tus metas y necesidades.", "Comunicación clara y procesos basados en integridad.", "Herramientas modernas para información oportuna."],
    steps: ["Conocemos tu negocio", "Evaluamos y planificamos", "Implementamos soluciones", "Monitoreamos y optimizamos", "Impulsamos tu crecimiento"], stepText: ["Entendemos tus objetivos y desafíos financieros.", "Analizamos tu situación y definimos la estrategia.", "Ponemos en marcha procesos eficientes y cumplidores.", "Damos seguimiento continuo para detectar resultados.", "Te acompañamos para que sigas creciendo con solidez."],
    industries: ["Comercio y retail", "Construcción", "Salud", "Restaurantes", "Profesionales", "Servicios", "E-commerce"], partners: ["Servicios legales", "Seguros", "Banca", "Tecnología", "Nómina", "Comunidad empresarial"],
  },
  en: {
    nav: ["Home", "Services", "About us", "Industries", "Resources", "Contact"], schedule: "Schedule a consultation", skip: "Skip to content", eyebrow: "Accounting, tax and business solutions",
    hero: "We build stronger businesses.", heroAccent: "We protect your growth.", heroText: "Clear, strategic advisory for entrepreneurs, growing companies and investors operating across the United States and Colombia.", discover: "Discover our services",
    servicesLabel: "Our services", servicesTitle: "Clearer decisions. Stronger businesses.", servicesText: "Integrated solutions for your obligations, structure and the next step of your business.",
    coverageLabel: "Coverage", coverageTitle: "We work with you in the United States and Colombia.", coverageNote: "Each service is confirmed based on your circumstances, jurisdiction and needs.",
    planningLabel: "Tax planning", planningTitle: "Tax decisions are planned before you file.", planningText: "A tailored strategy helps identify opportunities, anticipate obligations and make decisions with greater clarity.", planningDisclosure: "General educational information; it is not individualized tax or legal advice.", planningCta: "Request a tax review",
    resourcesLabel: "Tips & resources", resourcesTitle: "Information for better decisions.", resourcesText: "Practical content to understand your financial and tax situation. It does not replace personalized advice.", instagram: "View on Instagram", comingSoon: "Coming soon",
    videosLabel: "Learn with Contax", videosTitle: "Videos to move forward with confidence.", videosText: "A growing library of concise guides, explained in clear language.", allVideos: "View all videos",
    whyLabel: "Why Contax", whyTitle: "More than accountants, your strategic partners.", processLabel: "Our process", processTitle: "Five steps toward a better decision.",
    industriesLabel: "Industries we serve", industriesTitle: "Solutions that understand your operation.", partnersLabel: "Strategic partners", partnersTitle: "A network that expands your possibilities.", partnersText: "A space to present confirmed partners who complement each solution.",
    testimonialsLabel: "The confidence of our clients", testimonialsTitle: "Stories we will soon share.", testimonialsText: "We will publish testimonials with each client’s express approval.", share: "Share my experience",
    ctaLabel: "Let’s start a conversation", ctaTitle: "Ready for a clearer financial future?", ctaText: "Tell us where you are today and where you want your business to go. Let’s define the next step.",
    footerText: "Accounting, tax and business solutions with a long-term view.", explore: "Explore", contact: "Contact", legal: "All rights reserved.",
    services: ["Bookkeeping", "Personal & business taxes", "Business formation", "Payroll", "Accounting & financial advisory", "ITIN application assistance"],
    serviceText: ["Organized financial information to support better decisions.", "Preparation and guidance to comply with clarity.", "The right structure to start and grow with confidence.", "Organized, timely payroll processes.", "A strategic perspective for every phase of your business.", "Guidance through your ITIN process."],
    usa: ["Personal and business taxes", "ITIN for eligible individuals", "LLC and corporation formation", "Bookkeeping and payroll"], colombia: ["Bookkeeping and financial reports", "Tax and compliance guidance", "Business formalization", "Financial and strategic advisory"],
    resources: ["Tax planning", "How to organize deductible expenses", "Key dates for your business"], resourceTypes: ["INSTAGRAM REEL", "ARTICLE", "GUIDE"], videos: ["What is tax planning and why does your business need it?", "Tax deductions many owners overlook", "LLC vs. Corporation: which is best?", "ITIN: requirements and process step by step"],
    reasons: ["Experience and knowledge", "Personalized approach", "Trust and transparency", "Technology for you"], reasonText: ["Technical knowledge and practical experience to see the full picture.", "Solutions tailored to your goals and needs.", "Clear communication and processes grounded in integrity.", "Modern tools for timely information."],
    steps: ["We learn your business", "We assess and plan", "We implement solutions", "We monitor and optimize", "We accelerate your growth"], stepText: ["We understand your financial goals and challenges.", "We analyze your situation and define a strategy.", "We put efficient, compliant processes in motion.", "We follow up to identify results and adjustments.", "We stay close as you grow with strength."],
    industries: ["Retail and commerce", "Construction", "Healthcare", "Restaurants", "Professionals", "Services", "E-commerce"], partners: ["Legal services", "Insurance", "Banking", "Technology", "Payroll", "Business community"],
  },
};

const Arrow = () => <span aria-hidden="true">→</span>;
const Icon = ({ index }: { index: number }) => <span className="icon" aria-hidden="true">{["▦", "◇", "▤", "◎", "↗", "⊕"][index % 6]}</span>;
function Logo({ footer = false }: { footer?: boolean }) { return <Image className={footer ? "footer-logo" : "brand-logo"} src="/contax-logo.png" alt="Contax Business Solutions" width={500} height={120} priority />; }

export default function Home() {
  const [language, setLanguage] = useState<Language>("es");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const t = content[language];
  const list = (name: string) => t[name] as string[];
  useEffect(() => { const stored = localStorage.getItem("contax-language"); setLanguage(stored === "en" || stored === "es" ? stored : navigator.language.startsWith("es") ? "es" : "en"); }, []);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const changeLanguage = (next: Language) => { localStorage.setItem("contax-language", next); setLanguage(next); };
  const closeMobileMenu = () => setMobileMenuOpen(false);

  return <><a className="skip-link" href="#main-content">{t.skip as string}</a><main id="main-content">
    <section className="hero" id="top"><nav className="nav container" aria-label="Main navigation"><a className="brand" href="#top" onClick={closeMobileMenu}><Logo /></a><div className="nav-links"><a href="#top">{list("nav")[0]}</a><a href="#services">{list("nav")[1]}</a><a href="#why">{list("nav")[2]}</a><a href="#industries">{list("nav")[3]}</a><a href="#resources">{list("nav")[4]}</a><a href="#contact">{list("nav")[5]}</a></div><div className="nav-actions"><div className="language-switcher" aria-label="Language selector"><button className={language === "en" ? "active" : ""} onClick={() => changeLanguage("en")} aria-pressed={language === "en"}>EN</button><span>/</span><button className={language === "es" ? "active" : ""} onClick={() => changeLanguage("es")} aria-pressed={language === "es"}>ES</button></div><a className="nav-cta" href="#contact">{t.schedule as string} <Arrow /></a><button className="menu-toggle" type="button" aria-expanded={mobileMenuOpen} aria-controls="mobile-navigation" onClick={() => setMobileMenuOpen((open) => !open)}><span className="sr-only">{mobileMenuOpen ? "Cerrar menú" : "Abrir menú"}</span><i /><i /></button></div></nav><div className={mobileMenuOpen ? "mobile-menu is-open" : "mobile-menu"} id="mobile-navigation"><a href="#top" onClick={closeMobileMenu}>{list("nav")[0]}</a><a href="#services" onClick={closeMobileMenu}>{list("nav")[1]}</a><a href="#why" onClick={closeMobileMenu}>{list("nav")[2]}</a><a href="#industries" onClick={closeMobileMenu}>{list("nav")[3]}</a><a href="#resources" onClick={closeMobileMenu}>{list("nav")[4]}</a><a href="#contact" onClick={closeMobileMenu}>{list("nav")[5]}</a></div><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">{t.eyebrow as string}</p><h1>{t.hero as string}<br /><em>{t.heroAccent as string}</em></h1><p>{t.heroText as string}</p><div className="button-row"><a className="button gold" href="#contact">{t.schedule as string} <Arrow /></a><a className="inline-link light-link" href="#services">{t.discover as string} <Arrow /></a></div></div><div className="hero-symbol" aria-hidden="true"><Image src="/contax-isotype.png" alt="" width={420} height={420} priority /><div className="bars"><i /><i /><i /><i /></div></div></div><div className="hero-wave" aria-hidden="true" /></section>

    <section className="services section" id="services"><div className="container"><Header label={t.servicesLabel as string} title={t.servicesTitle as string} text={t.servicesText as string} /><div className="service-grid">{list("services").map((service, index) => <article className="service-card" key={service}><Icon index={index} /><h3>{service}</h3><p>{list("serviceText")[index]}</p><a href="#contact" aria-label={`${service}: ${t.schedule as string}`}><Arrow /></a></article>)}</div></div></section>
    <section className="coverage section" id="coverage"><div className="container"><div className="coverage-heading"><div><p className="section-kicker">✦ {t.coverageLabel as string}</p><h2>{t.coverageTitle as string}</h2></div><p>{t.coverageNote as string}</p></div><div className="country-grid"><Country name="Estados Unidos / United States" flag="🇺🇸" entries={list("usa")} /><Country name="Colombia" flag="🇨🇴" entries={list("colombia")} /><div className="map-mark" aria-hidden="true"><span>✦</span><b>US</b><i>CO</i></div></div></div></section>
    <section className="planning"><div className="container planning-grid"><div><p className="section-kicker gold-text">✦ {t.planningLabel as string}</p><h2>{t.planningTitle as string}</h2><p>{t.planningText as string}</p><div className="planning-points"><span>✓ {language === "es" ? "Preparación de impuestos" : "Tax preparation"}</span><span>✓ {language === "es" ? "Planeación tributaria" : "Tax planning"}</span></div><p className="disclaimer">{t.planningDisclosure as string}</p></div><div className="planning-seal" aria-hidden="true"><span>▤</span><i>✓</i></div><div className="planning-side"><ul><li>✓ {language === "es" ? "Analizamos tu situación y objetivos." : "We analyze your situation and goals."}</li><li>✓ {language === "es" ? "Diseñamos estrategias a tu medida." : "We design a strategy around you."}</li><li>✓ {language === "es" ? "Identificamos deducciones aplicables." : "We identify applicable deductions."}</li></ul><a className="button gold" href="#contact">{t.planningCta as string} <Arrow /></a></div></div></section>
    <section className="resources section" id="resources"><div className="container"><Header label={t.resourcesLabel as string} title={t.resourcesTitle as string} text={t.resourcesText as string} /><div className="resource-grid">{list("resources").map((title, index) => <article className={`resource-card ${index === 0 ? "featured" : ""}`} key={title}><p>{list("resourceTypes")[index]}</p>{index === 0 && <span className="instagram-mark">◎</span>}<h3>{title}</h3>{index === 0 ? <a href="https://www.instagram.com/reel/DWkVUxjkYXr/" target="_blank" rel="noreferrer">{t.instagram as string} <Arrow /></a> : <span className="muted-link">{t.comingSoon as string} <Arrow /></span>}</article>)}</div></div></section>
    <section className="video-section"><div className="container"><Header label={t.videosLabel as string} title={t.videosTitle as string} text={t.videosText as string} /><div className="video-grid">{list("videos").map((title, index) => <article className="video-card" key={title}><div className={`video-cover v${index + 1}`}><span>▶</span><small>{t.comingSoon as string}</small></div><p>{title}</p></article>)}</div><a className="inline-link dark-link center-link" href="#contact">{t.allVideos as string} <Arrow /></a></div></section>
    <section className="why section" id="why"><div className="container why-grid"><div><p className="section-kicker">✦ {t.whyLabel as string}</p><h2>{t.whyTitle as string}</h2></div><div className="reason-grid">{list("reasons").map((reason, index) => <article key={reason}><Icon index={index} /><div><h3>{reason}</h3><p>{list("reasonText")[index]}</p></div></article>)}</div></div></section>
    <section className="process" id="process"><div className="container"><Header label={t.processLabel as string} title={t.processTitle as string} /><div className="process-steps">{list("steps").map((step, index) => <article key={step}><span>{index + 1}</span><h3>{step}</h3><p>{list("stepText")[index]}</p></article>)}</div></div></section>
    <section className="industries section" id="industries"><div className="container"><Header label={t.industriesLabel as string} title={t.industriesTitle as string} /><div className="industry-grid">{list("industries").map((industry, index) => <article key={industry}><Icon index={index} /><span>{industry}</span></article>)}</div></div></section>
    <section className="partners section"><div className="container partner-testimonial-grid"><div><p className="section-kicker">✦ {t.partnersLabel as string}</p><h2>{t.partnersTitle as string}</h2><p>{t.partnersText as string}</p><div className="partner-grid">{list("partners").map((partner, index) => <div key={partner}><Icon index={index} /><span>{partner}</span></div>)}</div></div><div className="testimonial-empty"><p className="section-kicker">✦ {t.testimonialsLabel as string}</p><span className="quote-mark">“</span><h2>{t.testimonialsTitle as string}</h2><p>{t.testimonialsText as string}</p><a className="inline-link dark-link" href={`mailto:${siteConfig.contact.email}?subject=Testimonio%20Contax`}>{t.share as string} <Arrow /></a></div></div></section>
    <section className="cta" id="contact"><div className="container cta-grid"><div><p className="section-kicker light-kicker">✦ {t.ctaLabel as string}</p><h2>{t.ctaTitle as string}</h2></div><div><p>{t.ctaText as string}</p><div className="button-row"><a className="button gold" href={`mailto:${siteConfig.contact.email}?subject=Consulta%20Contax`}>{t.schedule as string} <Arrow /></a><a className="inline-link light-link" href={siteConfig.contact.phoneHref}>{siteConfig.contact.phoneDisplay}</a></div></div></div><div className="cta-wave" aria-hidden="true" /></section>
    <footer className="footer"><div className="container footer-grid"><div><a href="#top"><Logo footer /></a><p>{t.footerText as string}</p><a className="social" href={siteConfig.contact.instagramUrl} target="_blank" rel="noreferrer">Instagram {siteConfig.social.instagramHandle} ↗</a></div><div><p className="footer-label">{t.explore as string}</p><a href="#top">{list("nav")[0]}</a><a href="#services">{list("nav")[1]}</a><a href="#why">{list("nav")[2]}</a><a href="#industries">{list("nav")[3]}</a><a href="#resources">{list("nav")[4]}</a></div><div><p className="footer-label">{t.contact as string}</p><a href={siteConfig.contact.phoneHref}>{siteConfig.contact.phoneDisplay}</a><a href={`mailto:${siteConfig.contact.email}`}>{siteConfig.contact.email}</a><span>{siteConfig.contact.location}</span><span>{siteConfig.contact.businessHours}</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Contax Business Solutions LLC. {t.legal as string}</span><span>Política de Privacidad · Términos y Condiciones</span></div></footer>
  </main></>;
}

function Header({ label, title, text }: { label: string; title: string; text?: string }) { return <div className="heading centered"><p className="section-kicker">✦ {label} ✦</p><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Country({ name, flag, entries }: { name: string; flag: string; entries: string[] }) { return <article><span className="flag">{flag}</span><h3>{name}</h3><ul>{entries.map(entry => <li key={entry}>✓ {entry}</li>)}</ul></article>; }
